['len_char_q1' 'len_char_q2' 'len_char_diff' 'len_char_ratio' 'len_word_q1'
 'len_word_q2' 'len_word_diff' 'len_word_ratio' 'len_word_expt_stop_q1'
 'len_word_expt_stop_q2' 'len_word_expt_stop_diff'
 'len_word_expt_stop_ratio' 'common_lemmas_num' 'common_stems_num'
 'common_lemmas_num_no_stops' 'common_lemmas_ratio_no_stops'
 'common_lemmas_ratio' 'common_stems_ratio' 'stop_words_ratio_q1'
 'stop_words_ratio_q2' 'tokens_kulsinski' 'lemmas_token_sort_ratio'
 'lemmas_token_set_ratio' 'lemmas_WRatio' 'lemmas_partial_token_sort_ratio'
 'lemmas_QRatio' 'lemmas_partial_ratio' 'stems_token_sort_ratio'
 'stems_token_set_ratio' 'stems_WRatio' 'stems_partial_token_sort_ratio'
 'stems_QRatio' 'stems_partial_ratio' 'tokens_token_sort_ratio'
 'tokens_token_set_ratio' 'tokens_WRatio' 'tokens_partial_token_sort_ratio'
 'tokens_QRatio' 'tokens_partial_ratio' 'lemmas_sorensen'
 'lemmas_nlevenshtein' 'lemmas_levenshtein' 'stems_sorensen'
 'stems_nlevenshtein' 'stems_levenshtein' 'tokens_sorensen'
 'tokens_nlevenshtein' 'tokens_levenshtein'
 'w1_max_smooth_idf_dirty_lower_no_stops'
 'w2_max_smooth_idf_dirty_lower_no_stops'
 'w1_min_smooth_idf_dirty_lower_no_stops'
 'w2_min_smooth_idf_dirty_lower_no_stops'
 'w1_mean_smooth_idf_dirty_lower_no_stops'
 'w2_mean_smooth_idf_dirty_lower_no_stops'
 'w1_std_smooth_idf_dirty_lower_no_stops'
 'w2_std_smooth_idf_dirty_lower_no_stops'
 'w1_sum_smooth_idf_dirty_lower_no_stops'
 'w2_sum_smooth_idf_dirty_lower_no_stops'
 'w_share_smooth_idf_dirty_lower_no_stops'
 'w_share_ratio_1_smooth_idf_dirty_lower_no_stops'
 'w_share_ratio_3_smooth_idf_dirty_lower_no_stops'
 'w_means_log_smooth_idf_dirty_lower_no_stops'
 'w1_max_std_idf_dirty_lower_no_stops'
 'w2_max_std_idf_dirty_lower_no_stops'
 'w1_min_std_idf_dirty_lower_no_stops'
 'w2_min_std_idf_dirty_lower_no_stops'
 'w1_mean_std_idf_dirty_lower_no_stops'
 'w2_mean_std_idf_dirty_lower_no_stops'
 'w1_std_std_idf_dirty_lower_no_stops'
 'w2_std_std_idf_dirty_lower_no_stops'
 'w1_sum_std_idf_dirty_lower_no_stops'
 'w2_sum_std_idf_dirty_lower_no_stops'
 'w_share_std_idf_dirty_lower_no_stops'
 'w_share_ratio_1_std_idf_dirty_lower_no_stops'
 'w_share_ratio_3_std_idf_dirty_lower_no_stops'
 'w_means_log_std_idf_dirty_lower_no_stops' 'w1_max_smooth_idf_dirty_upper'
 'w2_max_smooth_idf_dirty_upper' 'w1_min_smooth_idf_dirty_upper'
 'w2_min_smooth_idf_dirty_upper' 'w1_mean_smooth_idf_dirty_upper'
 'w2_mean_smooth_idf_dirty_upper' 'w1_std_smooth_idf_dirty_upper'
 'w2_std_smooth_idf_dirty_upper' 'w1_sum_smooth_idf_dirty_upper'
 'w2_sum_smooth_idf_dirty_upper' 'w_share_smooth_idf_dirty_upper'
 'w_share_ratio_1_smooth_idf_dirty_upper'
 'w_share_ratio_3_smooth_idf_dirty_upper'
 'w_means_log_smooth_idf_dirty_upper' 'w1_max_std_idf_dirty_upper'
 'w2_max_std_idf_dirty_upper' 'w1_min_std_idf_dirty_upper'
 'w2_min_std_idf_dirty_upper' 'w1_mean_std_idf_dirty_upper'
 'w2_mean_std_idf_dirty_upper' 'w1_std_std_idf_dirty_upper'
 'w2_std_std_idf_dirty_upper' 'w1_sum_std_idf_dirty_upper'
 'w2_sum_std_idf_dirty_upper' 'w_share_std_idf_dirty_upper'
 'w_share_ratio_1_std_idf_dirty_upper'
 'w_share_ratio_3_std_idf_dirty_upper' 'w_means_log_std_idf_dirty_upper'
 'w1_max_smooth_idf_tokens_lower' 'w2_max_smooth_idf_tokens_lower'
 'w1_min_smooth_idf_tokens_lower' 'w2_min_smooth_idf_tokens_lower'
 'w1_mean_smooth_idf_tokens_lower' 'w2_mean_smooth_idf_tokens_lower'
 'w1_std_smooth_idf_tokens_lower' 'w2_std_smooth_idf_tokens_lower'
 'w1_sum_smooth_idf_tokens_lower' 'w2_sum_smooth_idf_tokens_lower'
 'w_share_smooth_idf_tokens_lower'
 'w_share_ratio_1_smooth_idf_tokens_lower'
 'w_share_ratio_3_smooth_idf_tokens_lower'
 'w_means_log_smooth_idf_tokens_lower' 'w1_max_std_idf_tokens_lower'
 'w2_max_std_idf_tokens_lower' 'w1_min_std_idf_tokens_lower'
 'w2_min_std_idf_tokens_lower' 'w1_mean_std_idf_tokens_lower'
 'w2_mean_std_idf_tokens_lower' 'w1_std_std_idf_tokens_lower'
 'w2_std_std_idf_tokens_lower' 'w1_sum_std_idf_tokens_lower'
 'w2_sum_std_idf_tokens_lower' 'w_share_std_idf_tokens_lower'
 'w_share_ratio_1_std_idf_tokens_lower'
 'w_share_ratio_3_std_idf_tokens_lower' 'w_means_log_std_idf_tokens_lower'
 'w1_max_smooth_idf_tokens_lower_no_stops'
 'w2_max_smooth_idf_tokens_lower_no_stops'
 'w1_min_smooth_idf_tokens_lower_no_stops'
 'w2_min_smooth_idf_tokens_lower_no_stops'
 'w1_mean_smooth_idf_tokens_lower_no_stops'
 'w2_mean_smooth_idf_tokens_lower_no_stops'
 'w1_std_smooth_idf_tokens_lower_no_stops'
 'w2_std_smooth_idf_tokens_lower_no_stops'
 'w1_sum_smooth_idf_tokens_lower_no_stops'
 'w2_sum_smooth_idf_tokens_lower_no_stops'
 'w_share_smooth_idf_tokens_lower_no_stops'
 'w_share_ratio_1_smooth_idf_tokens_lower_no_stops'
 'w_share_ratio_3_smooth_idf_tokens_lower_no_stops'
 'w_means_log_smooth_idf_tokens_lower_no_stops'
 'w1_max_std_idf_tokens_lower_no_stops'
 'w2_max_std_idf_tokens_lower_no_stops'
 'w1_min_std_idf_tokens_lower_no_stops'
 'w2_min_std_idf_tokens_lower_no_stops'
 'w1_mean_std_idf_tokens_lower_no_stops'
 'w2_mean_std_idf_tokens_lower_no_stops'
 'w1_std_std_idf_tokens_lower_no_stops'
 'w2_std_std_idf_tokens_lower_no_stops'
 'w1_sum_std_idf_tokens_lower_no_stops'
 'w2_sum_std_idf_tokens_lower_no_stops'
 'w_share_std_idf_tokens_lower_no_stops'
 'w_share_ratio_1_std_idf_tokens_lower_no_stops'
 'w_share_ratio_3_std_idf_tokens_lower_no_stops'
 'w_means_log_std_idf_tokens_lower_no_stops' 'freq_question1'
 'freq_question2' 'q1_q2_intersect' 'wh1' 'wh2' 'wh_same'
 'upper_plus_freq_200' 'upper_minus_freq_200' 'freq_50_plus_mean'
 'freq_50_plus_g_mean' 'freq_50_plus_len' 'freq_50_plus_std'
 'freq_50_plus_min' 'freq_50_plus_max' 'freq_50_plus_max_min_ratio'
 'freq_50_minus_mean' 'freq_50_minus_g_mean' 'freq_50_minus_len'
 'freq_50_minus_std' 'freq_50_minus_min' 'freq_50_minus_max'
 'freq_50_minus_max_min_ratio' 'freq_100_plus_mean' 'freq_100_plus_g_mean'
 'freq_100_plus_len' 'freq_100_plus_std' 'freq_100_plus_min'
 'freq_100_plus_max' 'freq_100_plus_max_min_ratio' 'freq_100_minus_mean'
 'freq_100_minus_g_mean' 'freq_100_minus_len' 'freq_100_minus_std'
 'freq_100_minus_min' 'freq_100_minus_max' 'freq_100_minus_max_min_ratio'
 'freq_200_plus_mean' 'freq_200_plus_g_mean' 'freq_200_plus_len'
 'freq_200_plus_std' 'freq_200_plus_min' 'freq_200_plus_max'
 'freq_200_plus_max_min_ratio' 'freq_200_minus_mean'
 'freq_200_minus_g_mean' 'freq_200_minus_len' 'freq_200_minus_std'
 'freq_200_minus_min' 'freq_200_minus_max' 'freq_200_minus_max_min_ratio'
 'freq_500_plus_mean' 'freq_500_plus_g_mean' 'freq_500_plus_len'
 'freq_500_plus_std' 'freq_500_plus_min' 'freq_500_plus_max'
 'freq_500_plus_max_min_ratio' 'freq_500_minus_mean'
 'freq_500_minus_g_mean' 'freq_500_minus_len' 'freq_500_minus_std'
 'freq_500_minus_min' 'freq_500_minus_max' 'freq_500_minus_max_min_ratio'
 'freq_1000_plus_mean' 'freq_1000_plus_g_mean' 'freq_1000_plus_len'
 'freq_1000_plus_std' 'freq_1000_plus_min' 'freq_1000_plus_max'
 'freq_1000_plus_max_min_ratio' 'freq_1000_minus_mean'
 'freq_1000_minus_g_mean' 'freq_1000_minus_len' 'freq_1000_minus_std'
 'freq_1000_minus_min' 'freq_1000_minus_max'
 'freq_1000_minus_max_min_ratio' 'abi_wmd' 'abi_norm_wmd'
 'abi_cosine_distance' 'abi_cityblock_distance' 'abi_canberra_distance'
 'abi_euclidean_distance' 'abi_minkowski_distance'
 'abi_braycurtis_distance' 'abi_skew_q1vec' 'abi_skew_q2vec'
 'abi_kur_q1vec' 'abi_kur_q2vec' 'q1_k_max_core' 'q2_k_max_core'
 'cosine_distance_tokens_word2vec' 'cityblock_distance_tokens_word2vec'
 'jaccard_distance_tokens_word2vec' 'canberra_distance_tokens_word2vec'
 'euclidean_distance_tokens_word2vec' 'minkowski_distance_tokens_word2vec'
 'braycurtis_distance_tokens_word2vec' 'skew_q1vec_tokens_word2vec'
 'skew_q2vec_tokens_word2vec' 'kur_q1vec_tokens_word2vec'
 'kur_q2vec_tokens_word2vec' 'cosine_distance_lemmas_word2vec'
 'cityblock_distance_lemmas_word2vec' 'canberra_distance_lemmas_word2vec'
 'euclidean_distance_lemmas_word2vec' 'minkowski_distance_lemmas_word2vec'
 'braycurtis_distance_lemmas_word2vec' 'skew_q1vec_lemmas_word2vec'
 'skew_q2vec_lemmas_word2vec' 'kur_q1vec_lemmas_word2vec'
 'kur_q2vec_lemmas_word2vec' 'word2vec_wmd_tokens' 'word2vec_wmd_lemmas'
 'word2vec_norm_wmd_tokens' 'word2vec_norm_wmd_lemmas'
 'cosine_distance_tokens_glove' 'cityblock_distance_tokens_glove'
 'canberra_distance_tokens_glove' 'euclidean_distance_tokens_glove'
 'minkowski_distance_tokens_glove' 'braycurtis_distance_tokens_glove'
 'skew_q1vec_tokens_glove' 'skew_q2vec_tokens_glove'
 'kur_q1vec_tokens_glove' 'kur_q2vec_tokens_glove'
 'cosine_distance_lemmas_glove' 'cityblock_distance_lemmas_glove'
 'canberra_distance_lemmas_glove' 'euclidean_distance_lemmas_glove'
 'minkowski_distance_lemmas_glove' 'braycurtis_distance_lemmas_glove'
 'skew_q1vec_lemmas_glove' 'skew_q2vec_lemmas_glove'
 'kur_q1vec_lemmas_glove' 'kur_q2vec_lemmas_glove' 'glove_wmd_tokens'
 'glove_wmd_lemmas' 'glove_norm_wmd_tokens' 'glove_norm_wmd_lemmas'
 'cosine_distance_tokens_lex' 'cityblock_distance_tokens_lex'
 'canberra_distance_tokens_lex' 'euclidean_distance_tokens_lex'
 'minkowski_distance_tokens_lex' 'braycurtis_distance_tokens_lex'
 'skew_q1vec_tokens_lex' 'skew_q2vec_tokens_lex' 'kur_q1vec_tokens_lex'
 'kur_q2vec_tokens_lex' 'cosine_distance_lemmas_lex'
 'cityblock_distance_lemmas_lex' 'canberra_distance_lemmas_lex'
 'euclidean_distance_lemmas_lex' 'minkowski_distance_lemmas_lex'
 'braycurtis_distance_lemmas_lex' 'skew_q1vec_lemmas_lex'
 'skew_q2vec_lemmas_lex' 'kur_q1vec_lemmas_lex' 'kur_q2vec_lemmas_lex'
 'lex_wmd_tokens' 'lex_wmd_lemmas' 'lex_norm_wmd_tokens'
 'lex_norm_wmd_lemmas' 'aux_pair_target_freq'
 'kur_vec_tokens_word2vec_abs_diff' 'kur_vec_tokens_word2vec_1div2_ratio'
 'kur_vec_tokens_word2vec_log_ratio' 'kur_vec_tokens_word2vec_q1_ratio'
 'kur_vec_tokens_word2vec_q2_ratio' 'kur_vec_tokens_glove_abs_diff'
 'kur_vec_tokens_glove_1div2_ratio' 'kur_vec_tokens_glove_log_ratio'
 'kur_vec_tokens_glove_q1_ratio' 'kur_vec_tokens_glove_q2_ratio'
 'kur_vec_tokens_lex_abs_diff' 'kur_vec_tokens_lex_1div2_ratio'
 'kur_vec_tokens_lex_log_ratio' 'kur_vec_tokens_lex_q1_ratio'
 'kur_vec_tokens_lex_q2_ratio' 'kur_vec_lemmas_word2vec_abs_diff'
 'kur_vec_lemmas_word2vec_1div2_ratio' 'kur_vec_lemmas_word2vec_log_ratio'
 'kur_vec_lemmas_word2vec_q1_ratio' 'kur_vec_lemmas_word2vec_q2_ratio'
 'kur_vec_lemmas_glove_abs_diff' 'kur_vec_lemmas_glove_1div2_ratio'
 'kur_vec_lemmas_glove_log_ratio' 'kur_vec_lemmas_glove_q1_ratio'
 'kur_vec_lemmas_glove_q2_ratio' 'kur_vec_lemmas_lex_abs_diff'
 'kur_vec_lemmas_lex_1div2_ratio' 'kur_vec_lemmas_lex_log_ratio'
 'kur_vec_lemmas_lex_q1_ratio' 'kur_vec_lemmas_lex_q2_ratio'
 'skew_vec_tokens_word2vec_abs_diff' 'skew_vec_tokens_word2vec_1div2_ratio'
 'skew_vec_tokens_word2vec_log_ratio' 'skew_vec_tokens_word2vec_q1_ratio'
 'skew_vec_tokens_word2vec_q2_ratio' 'skew_vec_tokens_glove_abs_diff'
 'skew_vec_tokens_glove_1div2_ratio' 'skew_vec_tokens_glove_log_ratio'
 'skew_vec_tokens_glove_q1_ratio' 'skew_vec_tokens_glove_q2_ratio'
 'skew_vec_tokens_lex_abs_diff' 'skew_vec_tokens_lex_1div2_ratio'
 'skew_vec_tokens_lex_log_ratio' 'skew_vec_tokens_lex_q1_ratio'
 'skew_vec_tokens_lex_q2_ratio' 'skew_vec_lemmas_word2vec_abs_diff'
 'skew_vec_lemmas_word2vec_1div2_ratio'
 'skew_vec_lemmas_word2vec_log_ratio' 'skew_vec_lemmas_word2vec_q1_ratio'
 'skew_vec_lemmas_word2vec_q2_ratio' 'skew_vec_lemmas_glove_abs_diff'
 'skew_vec_lemmas_glove_1div2_ratio' 'skew_vec_lemmas_glove_log_ratio'
 'skew_vec_lemmas_glove_q1_ratio' 'skew_vec_lemmas_glove_q2_ratio'
 'skew_vec_lemmas_lex_abs_diff' 'skew_vec_lemmas_lex_1div2_ratio'
 'skew_vec_lemmas_lex_log_ratio' 'skew_vec_lemmas_lex_q1_ratio'
 'skew_vec_lemmas_lex_q2_ratio']
